CREATE TABLE IF NOT EXISTS `t_form_transfer_header` (
    `id` VARCHAR(32) NOT NULL,
    `company` VARCHAR(10) NULL,
    `plant` VARCHAR(20) NULL,
    `transaction_date` DATE NULL,
    `to_dept` VARCHAR(100) NULL,
    `from_dept` VARCHAR(100) NULL,
    `form_no` VARCHAR(45) NULL,
    `date_issued` DATE NULL,
    `revision_no` INT NULL,
    `revision_date` DATE NULL,
    `flag` CHAR(1) NULL,
    `entry_by` VARCHAR(50) NULL,
    `entry_date` DATETIME NULL,
    `prepared_by` VARCHAR(50) NULL,
    `prepared_date` DATETIME NULL,
    `prepared_status` VARCHAR(20) NULL,
    `prepared_status_remarks` VARCHAR(100) NULL,
    `checked_by` VARCHAR(50) NULL,
    `checked_date` DATETIME NULL,
    `checked_status` VARCHAR(20) NULL,
    `checked_status_remarks` VARCHAR(100) NULL,
    `approved_by` VARCHAR(50) NULL,
    `approved_date` DATETIME NULL,
    `approved_status` VARCHAR(20) NULL,
    `approved_status_remarks` VARCHAR(100) NULL,
    `acknowledged_by` VARCHAR(50) NULL,
    `acknowledged_date` DATETIME NULL,
    `acknowledged_status` VARCHAR(20) NULL,
    `acknowledged_status_remarks` VARCHAR(100) NULL,
    `updated_by` VARCHAR(50) NULL,
    `updated_date` DATETIME NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
